##
# stage 1
##
FROM node:14-alpine as static
WORKDIR /build
COPY ./frontend-search /build
RUN yarn install
RUN yarn build

##
# stage 2
##
FROM python:3.10-slim-buster as final

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

 RUN apt-get update \
   # dependencies for building Python packages
   && apt-get install -y build-essential \
   # tools
   && apt-get install -y curl \
   # psycopg2 dependencies
   # && apt-get install -y libpq-dev \
   # Translations dependencies
   #&& apt-get install -y gettext \
   # cleaning up unused files
   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
   && rm -rf /var/lib/apt/lists/*


# timezone to Asia/Taipei
RUN ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN echo "Asia/Taipei" > /etc/timezone
ENV TZ=Asia/Taipei

WORKDIR /code

# Package
#ENV VIRTUAL_ENV=/opt/venv
#RUN python3 -m venv $VIRTUAL_ENV
#ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements/prod.txt

COPY ./scripts/entrypoint /srv/entrypoint
RUN sed -i 's/\r$//g' /srv/entrypoint
RUN chmod +x /srv/entrypoint

COPY ./scripts/start /srv/start
RUN sed -i 's/\r$//g' /srv/start
RUN chmod +x /srv/start

COPY --from=static /build/dist /build/js

ENTRYPOINT ["/srv/entrypoint"]
