# Generated by Django 3.1.7 on 2021-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0002_auto_20210305_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='altitude',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
