# Generated by Django 4.0.4 on 2022-05-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0003_image_specific_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='folder_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
