# Generated by Django 3.1.7 on 2021-03-05 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0003_auto_20210305_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deployments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deployment'),
        ),
    ]
