# Generated by Django 3.1.7 on 2021-03-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0004_image_deployments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='deployments',
            new_name='deployment',
        ),
    ]
