# Generated by Django 4.0.4 on 2022-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0004_deploymentjournal_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='local_source_id',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
