# Generated by Django 4.0.4 on 2022-05-03 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0005_deploymentjournal_local_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deployment_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deploymentjournal'),
        ),
    ]
