# Generated by Django 3.1.7 on 2021-03-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0005_auto_20210305_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
