# Generated by Django 3.1.7 on 2021-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0006_image_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
