# Generated by Django 4.0.4 on 2022-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0006_image_deployment_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotation_seq',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
