# Generated by Django 4.0.4 on 2022-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0007_image_annotation_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
