# Generated by Django 3.1.7 on 2021-05-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0007_image_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='study_areas',
            field=models.ManyToManyField(blank=True, to='taicat.StudyArea'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taicat.studyarea'),
        ),
        migrations.AlterField(
            model_name='studyarea',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studyareas', to='taicat.project'),
        ),
    ]
