# Generated by Django 4.0.4 on 2022-05-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0008_deploymentjournal_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
