# Generated by Django 3.1.7 on 2021-05-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0009_auto_20210506_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo_type',
            field=models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('set-up', 'Set Up'), ('blank', 'Blank'), ('animal', 'Animal'), ('staff', 'Staff'), ('unknown', 'Unknown'), ('unidentifiable', 'Unidentifiable'), ('time-lapse', 'Timelapse')], max_length=100, null=True),
        ),
    ]
