# Generated by Django 4.0.4 on 2022-05-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0009_deploymentjournal_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedimage',
            name='annotation_seq',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='deletedimage',
            name='deployment_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deploymentjournal'),
        ),
        migrations.AddField(
            model_name='deletedimage',
            name='has_storage',
            field=models.CharField(blank=True, default='Y', max_length=2, verbose_name='實體檔案(有無上傳)'),
        ),
        migrations.AddField(
            model_name='deletedimage',
            name='specific_bucket',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='deployment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='taicat.deployment'),
        ),
    ]
