# Generated by Django 3.2.2 on 2021-05-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0010_auto_20210506_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
