# Generated by Django 4.0.4 on 2022-05-20 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0010_deletedimage_annotation_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentjournal',
            name='gap_caused',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='缺失原因'),
        ),
        migrations.AlterField(
            model_name='deploymentjournal',
            name='is_gap',
            field=models.BooleanField(default=False, verbose_name='缺失'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='taicat.project'),
        ),
    ]
