# Generated by Django 4.0.4 on 2022-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0011_alter_deploymentjournal_gap_caused_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(db_index=True, max_length=10)),
                ('num_project', models.IntegerField(blank=True, null=True)),
                ('num_deployment', models.IntegerField(blank=True, null=True)),
                ('num_image', models.IntegerField(blank=True, null=True)),
                ('num_working_hour', models.IntegerField(blank=True, null=True)),
                ('identified', models.FloatField(blank=True, null=True)),
                ('species', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deployment',
            name='geodetic_datum',
            field=models.CharField(choices=[('TWD97', 'TWD97'), ('WGS84', 'WGS84')], default='WGS84', max_length=10),
        ),
    ]
