# Generated by Django 4.0.4 on 2022-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0012_geostat_alter_deployment_geodetic_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='geostat',
            name='studyarea',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
