# Generated by Django 3.2.2 on 2021-07-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0012_auto_20210709_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='taicat.Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, choices=[('system_admin', '系統管理員'), ('organization_admin', '計畫總管理人'), ('project_admin', '個別計畫承辦人'), ('uploader', '資料上傳者'), ('general', '一般使用者')], max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('projects', models.ManyToManyField(to='taicat.Project')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.organization'),
        ),
    ]
