# Generated by Django 4.0.4 on 2022-05-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0013_geostat_studyarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAreaStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('studyarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea')),
            ],
        ),
    ]
