# Generated by Django 3.2.2 on 2021-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0014_auto_20210709_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='計畫編號'),
        ),
        migrations.AddField(
            model_name='project',
            name='executive_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='執行單位'),
        ),
        migrations.AddField(
            model_name='project',
            name='identification_information_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='鑑定資訊'),
        ),
        migrations.AddField(
            model_name='project',
            name='interpretive_data_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='詮釋資料'),
        ),
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='計畫關鍵字'),
        ),
        migrations.AddField(
            model_name='project',
            name='publish_time',
            field=models.DateField(blank=True, null=True, verbose_name='公開日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='計畫簡稱'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_material_license',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='影像資料'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='計畫時間-結束'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='委辦單位'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='計畫名稱'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_investigator',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='計畫主持人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='計畫地區'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='計畫時間-開始'),
        ),
    ]
