# Generated by Django 3.2.2 on 2021-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0015_auto_20210716_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='計畫摘要'),
        ),
    ]
