# Generated by Django 4.0.4 on 2022-11-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0016_deployment_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
