# Generated by Django 3.2.2 on 2021-07-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0016_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
    ]
