# Generated by Django 4.0.4 on 2023-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0017_alter_image_options_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='upload_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
