# Generated by Django 3.2.2 on 2021-07-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0018_auto_20210716_0828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
    ]
