# Generated by Django 4.0.4 on 2023-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0018_deploymentjournal_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='studyareas',
            field=models.ManyToManyField(to='taicat.studyarea'),
        ),
    ]
