# Generated by Django 3.2.2 on 2021-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0019_rename_projectmembers_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_organization_admin',
            field=models.BooleanField(default=False, verbose_name='是否為計畫總管理人'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_system_admin',
            field=models.BooleanField(default=False, verbose_name='是否能進入林務局管考系統'),
        ),
    ]
