# Generated by Django 4.0.4 on 2023-03-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0019_projectmember_studyareas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='studyareas',
            new_name='pm_studyarea',
        ),
    ]
