# Generated by Django 4.0.4 on 2023-03-17 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0020_rename_studyareas_projectmember_pm_studyarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='pm_studyarea',
            new_name='pmstudyarea',
        ),
    ]
