# Generated by Django 4.0.4 on 2023-03-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0021_rename_pm_studyarea_projectmember_pmstudyarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='county',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='protectedarea',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='國家公園/保護留區'),
        ),
    ]
