# Generated by Django 3.2.2 on 2021-07-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0022_remove_contact_is_forestry_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.organization'),
        ),
    ]
