# Generated by Django 4.0.4 on 2023-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0022_deployment_county_deployment_protectedarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='參數名稱')),
                ('type', models.CharField(blank=True, choices=[('study_area', '樣區'), ('county', '縣市'), ('protected_area', '保護留區'), ('landcover', '植被類型'), ('identity', '使用者身份')], max_length=1000, null=True, verbose_name='參數範圍')),
                ('pmajor', models.CharField(blank=True, max_length=1000, null=True, verbose_name='上階層名稱')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='參數描述')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
