# Generated by Django 3.2.2 on 2021-07-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0023_project_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization_name',
        ),
    ]
