# Generated by Django 4.0.4 on 2023-03-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0024_parametercode_parametername_alter_parametercode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametercode',
            name='type',
            field=models.CharField(blank=True, choices=[('study_area', '樣區'), ('county', '縣市'), ('protected_area', '保護留區'), ('vegetation', '植被類型'), ('identity', '使用者身份')], max_length=1000, null=True, verbose_name='參數範圍'),
        ),
    ]
