# Generated by Django 3.2.2 on 2021-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0024_remove_project_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_login',
            field=models.BooleanField(default=True, verbose_name='登入狀態'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='orcid',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
