# Generated by Django 3.2.2 on 2021-07-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0025_auto_20210720_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_login',
        ),
    ]
