# Generated by Django 3.2.2 on 2021-07-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0026_remove_contact_is_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='publish_time',
            new_name='publish_date',
        ),
    ]
