# Generated by Django 4.0.4 on 2023-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0027_rename_identify_contact_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='altitude',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='protectedarea',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='國家公園/保護留區'),
        ),
    ]
