# Generated by Django 3.2.2 on 2021-07-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0027_rename_publish_time_project_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='projects',
            new_name='project',
        ),
    ]
