# Generated by Django 3.2.2 on 2021-07-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0028_rename_projects_projectmember_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='members',
            new_name='member',
        ),
    ]
