# Generated by Django 4.0.4 on 2023-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0028_alter_deployment_altitude_alter_deployment_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='calculation_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
