# Generated by Django 3.2.2 on 2021-07-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0030_auto_20210722_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
    ]
