# Generated by Django 4.0.4 on 2023-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0030_calculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='event_inverval',
            new_name='event_interval',
        ),
    ]
