# Generated by Django 3.2.2 on 2021-07-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0031_auto_20210722_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.CharField(blank=True, choices=[('test', '測試'), ('official', '正式')], default='official', max_length=8, null=True),
        ),
    ]
