# Generated by Django 4.0.4 on 2023-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0031_rename_event_inverval_calculation_event_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='working_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='working days'),
            preserve_default=False,
        ),
    ]
