# Generated by Django 4.0.4 on 2023-04-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0032_calculation_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='datetime_from',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calculation',
            name='datetime_to',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
