# Generated by Django 3.2.2 on 2021-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0032_alter_project_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='geodetic_datum',
            field=models.CharField(choices=[('TWD97', 'TWD97'), ('WGS84', 'WGS84')], default='TWD97', max_length=10),
        ),
        migrations.AddField(
            model_name='deployment',
            name='landcover',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='土地覆蓋類型'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='vegetation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='植被類型'),
        ),
    ]
