# Generated by Django 4.0.4 on 2023-04-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0033_calculation_datetime_from_calculation_datetime_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='month',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='year',
        ),
    ]
