# Generated by Django 3.2.2 on 2021-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0033_auto_20210726_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
