# Generated by Django 3.2.2 on 2021-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0034_alter_deployment_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
