# Generated by Django 4.0.4 on 2023-04-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0034_remove_calculation_month_remove_calculation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='working_days',
        ),
    ]
