# Generated by Django 4.0.4 on 2023-04-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0035_remove_calculation_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='使用者角色')),
                ('condiction', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='篩選條件')),
                ('file_link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='下載連結')),
            ],
        ),
    ]
