# Generated by Django 3.2.2 on 2021-07-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0035_auto_20210726_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='study_areas',
        ),
        migrations.AddField(
            model_name='deployment',
            name='study_areas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea'),
        ),
    ]
