# Generated by Django 3.2.2 on 2021-07-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0036_auto_20210726_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='study_areas',
            new_name='study_area',
        ),
    ]
