# Generated by Django 4.0.4 on 2023-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0036_downloadlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadlog',
            old_name='condiction',
            new_name='condition',
        ),
    ]
