# Generated by Django 4.0.4 on 2023-08-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0037_rename_condiction_downloadlog_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='status',
        ),
        migrations.AddField(
            model_name='species',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
