# Generated by Django 3.2.2 on 2021-07-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0037_rename_study_areas_deployment_study_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='verbatim_locality',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
