# Generated by Django 4.0.4 on 2023-08-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0038_remove_species_status_species_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagestat',
            name='type',
        ),
        migrations.AlterField(
            model_name='parametercode',
            name='type',
            field=models.CharField(blank=True, choices=[('study_area', '樣區'), ('county', '縣市'), ('protectedarea', '保護留區'), ('vegetation', '植被類型'), ('identity', '使用者身份')], max_length=1000, null=True, verbose_name='參數類型'),
        ),
    ]
