# Generated by Django 3.2.2 on 2021-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0038_deployment_verbatim_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
