# Generated by Django 3.2.2 on 2021-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0039_image_exif'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='from_mongo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
