# Generated by Django 3.2.8 on 2021-10-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0040_image_from_mongo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
