# Generated by Django 3.2.8 on 2021-10-19 06:00

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0041_auto_20211015_0341'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=django.contrib.postgres.indexes.GinIndex(fields=['annotation'], name='taicat_imag_annotat_280c10_gin'),
        ),
    ]
