# Generated by Django 3.2.8 on 2021-10-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0043_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='raw',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
