# Generated by Django 3.2.8 on 2021-10-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0045_alter_stat_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
