# Generated by Django 3.2.8 on 2021-10-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0046_delete_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project'),
        ),
    ]
