# Generated by Django 3.2.8 on 2021-10-20 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0047_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='studyarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea'),
        ),
    ]
