# Generated by Django 3.2.8 on 2021-10-21 03:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0048_image_studyarea'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
