# Generated by Django 3.2.8 on 2021-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0049_alter_project_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, default='', max_length=4, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
