# Generated by Django 3.2.8 on 2021-10-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0050_auto_20211021_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
