# Generated by Django 3.2.8 on 2021-10-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0051_alter_species_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('type', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Image_info',
            new_name='ImageInfo',
        ),
        migrations.CreateModel(
            name='ProjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sa', models.IntegerField(blank=True, null=True)),
                ('num_deployment', models.IntegerField(blank=True, null=True)),
                ('num_image', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project')),
            ],
        ),
    ]
