# Generated by Django 3.2.8 on 2021-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0051_alter_species_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
