# Generated by Django 3.2.8 on 2021-10-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0052_auto_20211022_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagestat',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
