# Generated by Django 3.2.8 on 2021-10-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0053_homepagestat_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagestat',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
