# Generated by Django 3.2.8 on 2021-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0056_alter_image_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagestat',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstat',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='species',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=4, null=True),
        ),
    ]
