# Generated by Django 3.2.8 on 2021-10-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0057_auto_20211022_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(db_index=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project')),
            ],
        ),
    ]
