# Generated by Django 3.2.8 on 2021-11-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0058_projectspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
