# Generated by Django 3.2.8 on 2021-11-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0059_image_folder_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='folder_path',
            new_name='file_path',
        ),
    ]
