# Generated by Django 3.2.10 on 2021-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0060_rename_folder_path_image_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='folder_name',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
