# Generated by Django 3.2.10 on 2022-02-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0061_auto_20220207_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='animal_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='antler',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='count',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='life_stage',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='remarks',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='sex',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='species',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True),
        ),
    ]
