# Generated by Django 3.2.10 on 2021-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0061_image_folder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_start', models.DateTimeField(auto_now_add=True)),
                ('working_end', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deployment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project')),
                ('studyarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea')),
            ],
        ),
    ]
