# Generated by Django 3.2.12 on 2022-02-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0062_auto_20220207_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
