# Generated by Django 3.2.10 on 2021-12-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0062_deploymentjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentjournal',
            name='working_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deploymentjournal',
            name='working_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
