# Generated by Django 3.2.10 on 2021-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0063_auto_20211216_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentjournal',
            name='is_effective',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='deploymentjournal',
            name='working_unformat',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
