# Generated by Django 3.2.12 on 2022-02-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0063_image_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstat',
            old_name='num_image',
            new_name='num_data',
        ),
    ]
