# Generated by Django 3.2.12 on 2022-02-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0064_rename_num_image_projectstat_num_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstat',
            name='earliest_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstat',
            name='latest_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
