# Generated by Django 3.2.10 on 2021-12-17 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0064_auto_20211216_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('month', models.SmallIntegerField(blank=True, null=True)),
                ('count_working_hour', models.SmallIntegerField(blank=True, null=True)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deployment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project')),
                ('studyarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea')),
            ],
        ),
    ]
