# Generated by Django 3.2.12 on 2022-02-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0065_auto_20220209_0919'),
        ('taicat', '0065_deploymentstat'),
    ]

    operations = [
    ]
