# Generated by Django 3.2.12 on 2022-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0067_auto_20220217_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
