# Generated by Django 3.2.12 on 2022-02-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0068_alter_image_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefolder',
            name='folder_last_updated',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagefolder',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
