# Generated by Django 3.2.12 on 2022-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0069_auto_20220218_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='folder_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
