# Generated by Django 3.2.12 on 2022-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0070_alter_image_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentstat',
            name='session',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
