# Generated by Django 3.2.12 on 2022-02-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0070_alter_image_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_info',
            name='image',
        ),
    ]
