# Generated by Django 3.2.12 on 2022-03-02 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0071_remove_image_info_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=1000, null=True)),
                ('filename', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(db_index=True, null=True)),
                ('photo_type', models.CharField(choices=[('start', 'Start'), ('end', 'End'), ('set-up', 'Set Up'), ('blank', 'Blank'), ('animal', 'Animal'), ('staff', 'Staff'), ('unknown', 'Unknown'), ('unidentifiable', 'Unidentifiable'), ('time-lapse', 'Timelapse')], max_length=100, null=True)),
                ('count', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('species', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('sequence_definition', models.CharField(blank=True, default='', max_length=1000)),
                ('life_stage', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('sex', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('antler', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('remarks', models.TextField(blank=True, db_index=True, default='', null=True)),
                ('animal_id', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('remarks2', models.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('annotation', models.JSONField(blank=True, db_index=True, default=dict)),
                ('memo', models.TextField(blank=True, default='')),
                ('image_hash', models.TextField(blank=True, default='')),
                ('from_mongo', models.BooleanField(blank=True, default=False)),
                ('image_uuid', models.CharField(blank=True, db_index=True, default='', max_length=1000, null=True)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('exif', models.JSONField(blank=True, default=dict)),
                ('folder_name', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deployment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deletedimage')),
                ('studyarea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.studyarea')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
