# Generated by Django 3.2.12 on 2022-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0073_deploymentstat_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_info',
            name='image_uuid',
            field=models.CharField(default='', max_length=1000, primary_key=True, serialize=False),
        ),
    ]
