# Generated by Django 3.2.12 on 2022-04-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0074_auto_20220311_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sequence_definition',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image_info',
            name='image_uuid',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
