# Generated by Django 3.2.12 on 2022-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0075_auto_20220413_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_info',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
