# Generated by Django 4.0.4 on 2022-05-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taicat', '0006_image_deployment_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('uploading', '上傳中'), ('finished', '已完成'), ('unfinished', '未完成')], max_length=10, null=True)),
                ('deployment_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.deploymentjournal')),
            ],
        ),
    ]
