# Generated by Django 4.0.4 on 2022-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploadhistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='error_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
