# Generated by Django 4.0.4 on 2022-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploadhistory_error_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='error_type',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='species_error',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='upload_error',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
