# Generated by Django 4.0.4 on 2022-05-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0006_image_deployment_journal'),
        ('base', '0004_remove_uploadhistory_error_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('is_readed', models.BooleanField(blank=True, default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.contact')),
                ('upload_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.uploadhistory')),
            ],
        ),
    ]
