# Generated by Django 4.0.4 on 2022-05-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taicat', '0014_studyareastat'),
        ('base', '0007_uploadnotification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadnotification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taicat.project'),
        ),
    ]
