# Generated by Django 4.0.4 on 2023-02-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_uploadnotification_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('version', models.FloatField(null=True, verbose_name='版本號')),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
