# Generated by Django 4.0.4 on 2023-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='版本號'),
        ),
    ]
