# Generated by Django 4.0.4 on 2023-02-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_announcement_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
