# Generated by Django 4.0.4 on 2023-02-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='版本更新說明'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='公告內容'),
        ),
    ]
