# Generated by Django 4.0.4 on 2023-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_announcement_mod_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('uploading', '上傳中'), ('finished', '已完成'), ('unfinished', '未完成')], max_length=10, null=True),
        ),
    ]
